---
title: "Analyse des ventes du produit"
author: "Ibrahima Bodian"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/SD SEM2/EXAM_PROGSTAT")
```

# bibliothèques
```{r libraries}
library(ggplot2)
library(dplyr)
library(readr)
```

# Fonction pour lire les fichiers CSV
```{r}
lire_donnees_ventes<-function(chemin_dossier, date_debut, date_fin){
  fichiers<-list.files(chemin_dossier, pattern="*.csv", full.names = TRUE)
  
  donnees<-fichiers %>%
    lapply(function(fichier){
      read_csv(fichier, show_col_types=FALSE, name_repair="minimal") %>%
        select(date, an, mois, jour, semaine, produit, type, nb_de_ventes) %>% 
        mutate(date = as.Date(date))
    }) %>%
    bind_rows()
  donnees<-donnees %>%
    filter(date>=as.Date(date_debut) & date<=as.Date(date_fin))
  return(donnees)
}

```

# Chargement des données
```{r}
chemin_dossier<-"exam_data"
donnees_ventes<-lire_donnees_ventes(chemin_dossier, "2020-01-01", "2024-12-31")
head(donnees_ventes)
```

# Visualisation
```{r}
generer_graphique_ventes<-function(donnees) {
  ggplot(donnees, aes(x=date, y=nb_de_ventes))+
    geom_line(color="blue", size=1)+
    labs(
      title = "Évolut° des ventes du produit",
      x = "Date",
      y = "Nbr de ventes",
      caption = "Source: Données de ventes (2020-2024)"
    )+
    theme_minimal()
}
```

```{r}
graphique_ventes<-generer_graphique_ventes(donnees_ventes)
graphique_ventes
ggsave("evolution_ventes.png", plot, width = 10, height = 6)
```